name: progress_button
description: A Flutter package that creates a progress button with smooth animation with the supplied value in percentage.
version: 0.0.1
homepage: https://github.com/shrijanRegmi/progress_button
repository: https://github.com/shrijanRegmi/progress_button

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
